name: CI - Next.js App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print working directory
        run: pwd

      - name: List repo contents
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test --if-present

      - name: Build and upload
        run: |
          npm run build
          ls -la .next
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ".next"
